grpo_sys_template: |-
    An agent system is provided with a set of memories and has tried to solve problems multiple times. 
    Since **concise** memory entries will be helpful to the agent system.
    From the reflections, we have got some raw memories. 
    Your task is to collect and think for the final memory revision plan. 
    Please give the **minimum** revision plan.
    You should provide at most 3 revisions.
   
    Each final memory must satisfy the following requirements:
    1. Choose the **minimum** revision.
    2. It must be clear, **generalizable** lessons for this case.The description sessions should be no more than **50** words
    3. Begin with **general** background with several words in the memory
    4. Focus on strategic thinking patterns, not specific calculations
    5. Emphasize decision points that could apply to similar problems
    6. Avoid repeating saying similar memory in multiple different memories
    
    When two memories conflict with each other, follow these rules:
    1.If the two memories apply to different scenarios, merge and generalize them.
    2.Else,use your own knowledge and judgment when making the decision.

    Use your own knowledge and judgment when making the decision.
   
    
    Please think for how to update existing experiences,
    You have three update options: [modify, merge, delete]
    - modify: You can modify current experiences to make it helpful
    - merge: You can merge some similar experiences into a more general forms to reduce duplication
   
    The memory format:
    ```  
    # Memory Item i
    ## Title: <the title of the memory item>  
    ## Description: Enum[Reasoning,Structure,Knowledge]
    ## Content: <1-3 sentences describing the insights learned to successfully accomplishing the task> 
    ```
    
    
grpo_user_template: |-
    Raw memory:
    <memory> 
    {{memories}} 
    </memory>

    Your output should follow the format shown below exactly(provide no more than 3 revision):
    
    ```json
    [
        {
            "option": "modify",
            "modified_id": "2", //An int.For Memory Item i,its id is i(an int).
            "title":"modified title",
            "description":"modified description",
            "content":"modified content",
            "think":"your thought",
        },
        {
            "option": "merge",
            "merged_id": ["1", "3", "4"],  //An int list.For Memory Item i,its id is i(an int).
            "title":"merged title",
            "description":"merged description",
            "content":"merged content",
            "think":"your thought",
        },
        {
            "option": "delete",
            "deleted_id": "5",//an int
            "think":"your thought",
        }, 
    ]
    ```